/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'date' : bigint,
  'published' : boolean,
  'author' : string,
  'coverImage' : ExternalBlob,
  'category' : string,
}
export interface Booking {
  'id' : string,
  'name' : string,
  'travelDates' : string,
  'travelers' : bigint,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
  'packageId' : string,
}
export type ExternalBlob = Uint8Array;
export interface GalleryPhoto {
  'id' : string,
  'title' : string,
  'description' : string,
  'image' : ExternalBlob,
}
export interface GalleryVideo {
  'id' : string,
  'title' : string,
  'description' : string,
  'youtubeUrl' : string,
}
export interface LeadCapture {
  'id' : string,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
  'packageId' : string,
}
export interface Review {
  'id' : string,
  'name' : string,
  'reviewText' : string,
  'approved' : boolean,
  'timestamp' : bigint,
  'rating' : bigint,
}
export type TourCategory = { 'domestic' : null } |
  { 'international' : null } |
  { 'honeymoon' : null };
export interface TourPackage {
  'id' : string,
  'title' : string,
  'duration' : string,
  'description' : string,
  'highlights' : Array<string>,
  'category' : TourCategory,
  'image' : ExternalBlob,
  'price' : bigint,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    string
  >,
  'addGalleryPhoto' : ActorMethod<[string, string, ExternalBlob], string>,
  'addGalleryVideo' : ActorMethod<[string, string, string], string>,
  'addTourPackage' : ActorMethod<
    [string, string, bigint, string, Array<string>, TourCategory, ExternalBlob],
    string
  >,
  'approveReview' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteBooking' : ActorMethod<[string], undefined>,
  'deleteGalleryPhoto' : ActorMethod<[string], undefined>,
  'deleteGalleryVideo' : ActorMethod<[string], undefined>,
  'deleteLeadCapture' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteTourPackage' : ActorMethod<[string], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllGalleryPhotos' : ActorMethod<[], Array<GalleryPhoto>>,
  'getAllGalleryVideos' : ActorMethod<[], Array<GalleryVideo>>,
  'getAllLeadCaptures' : ActorMethod<[], Array<LeadCapture>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllTourPackages' : ActorMethod<[], Array<TourPackage>>,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'publishBlogPost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitBooking' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    string
  >,
  'submitLeadCapture' : ActorMethod<[string, string, string, string], string>,
  'submitReview' : ActorMethod<[string, bigint, string], string>,
  'updateBlogPost' : ActorMethod<
    [string, string, string, string, string, ExternalBlob, boolean],
    undefined
  >,
  'updateGalleryPhoto' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'updateTourPackage' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
      TourCategory,
      ExternalBlob,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];