/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: string;
    title: string;
    content: string;
    date: bigint;
    published: boolean;
    author: string;
    coverImage: ExternalBlob;
    category: string;
}
export interface GalleryPhoto {
    id: string;
    title: string;
    description: string;
    image: ExternalBlob;
}
export interface UserProfile {
    name: string;
    email: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface TourPackage {
    id: string;
    title: string;
    duration: string;
    description: string;
    highlights: Array<string>;
    category: TourCategory;
    image: ExternalBlob;
    price: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LeadCapture {
    id: string;
    name: string;
    email: string;
    timestamp: bigint;
    phone: string;
    packageId: string;
}
export interface GalleryVideo {
    id: string;
    title: string;
    description: string;
    youtubeUrl: string;
}
export interface Booking {
    id: string;
    name: string;
    travelDates: string;
    travelers: bigint;
    email: string;
    message: string;
    timestamp: bigint;
    phone: string;
    packageId: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface Review {
    id: string;
    name: string;
    reviewText: string;
    approved: boolean;
    timestamp: bigint;
    rating: bigint;
}
export enum TourCategory {
    domestic = "domestic",
    international = "international",
    honeymoon = "honeymoon"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBlogPost(title: string, content: string, author: string, category: string, coverImage: ExternalBlob): Promise<string>;
    addGalleryPhoto(title: string, description: string, image: ExternalBlob): Promise<string>;
    addGalleryVideo(title: string, description: string, youtubeUrl: string): Promise<string>;
    addTourPackage(title: string, description: string, price: bigint, duration: string, highlights: Array<string>, category: TourCategory, image: ExternalBlob): Promise<string>;
    approveReview(id: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBlogPost(id: string): Promise<void>;
    deleteBooking(id: string): Promise<void>;
    deleteGalleryPhoto(id: string): Promise<void>;
    deleteGalleryVideo(id: string): Promise<void>;
    deleteLeadCapture(id: string): Promise<void>;
    deleteReview(id: string): Promise<void>;
    deleteTourPackage(id: string): Promise<void>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllGalleryPhotos(): Promise<Array<GalleryPhoto>>;
    getAllGalleryVideos(): Promise<Array<GalleryVideo>>;
    getAllLeadCaptures(): Promise<Array<LeadCapture>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllTourPackages(): Promise<Array<TourPackage>>;
    getApprovedReviews(): Promise<Array<Review>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPublishedBlogPosts(): Promise<Array<BlogPost>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    publishBlogPost(id: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitBooking(name: string, email: string, phone: string, travelDates: string, travelers: bigint, message: string, packageId: string): Promise<string>;
    submitLeadCapture(name: string, phone: string, email: string, packageId: string): Promise<string>;
    submitReview(name: string, rating: bigint, reviewText: string): Promise<string>;
    updateBlogPost(id: string, title: string, content: string, author: string, category: string, coverImage: ExternalBlob, published: boolean): Promise<void>;
    updateGalleryPhoto(id: string, title: string, description: string, image: ExternalBlob): Promise<void>;
    updateTourPackage(id: string, title: string, description: string, price: bigint, duration: string, highlights: Array<string>, category: TourCategory, image: ExternalBlob): Promise<void>;
}
import type { BlogPost as _BlogPost, ExternalBlob as _ExternalBlob, GalleryPhoto as _GalleryPhoto, TourCategory as _TourCategory, TourPackage as _TourPackage, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async addGalleryPhoto(arg0: string, arg1: string, arg2: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryPhoto(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryPhoto(arg0, arg1, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addGalleryVideo(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryVideo(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryVideo(arg0, arg1, arg2);
            return result;
        }
    }
    async addTourPackage(arg0: string, arg1: string, arg2: bigint, arg3: string, arg4: Array<string>, arg5: TourCategory, arg6: ExternalBlob): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourPackage(arg0, arg1, arg2, arg3, arg4, to_candid_TourCategory_n9(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourPackage(arg0, arg1, arg2, arg3, arg4, to_candid_TourCategory_n9(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async approveReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveReview(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async deleteGalleryPhoto(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryPhoto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryPhoto(arg0);
            return result;
        }
    }
    async deleteGalleryVideo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryVideo(arg0);
            return result;
        }
    }
    async deleteLeadCapture(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLeadCapture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLeadCapture(arg0);
            return result;
        }
    }
    async deleteReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteTourPackage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTourPackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTourPackage(arg0);
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return result;
        }
    }
    async getAllGalleryPhotos(): Promise<Array<GalleryPhoto>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryPhotos();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryPhotos();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryVideos(): Promise<Array<GalleryVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryVideos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryVideos();
            return result;
        }
    }
    async getAllLeadCaptures(): Promise<Array<LeadCapture>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeadCaptures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLeadCaptures();
            return result;
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return result;
        }
    }
    async getAllTourPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTourPackages();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTourPackages();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPosts();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPosts();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async publishBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishBlogPost(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async submitLeadCapture(arg0: string, arg1: string, arg2: string, arg3: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLeadCapture(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLeadCapture(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: bigint, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2);
            return result;
        }
    }
    async updateBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async updateGalleryPhoto(arg0: string, arg1: string, arg2: string, arg3: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryPhoto(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryPhoto(arg0, arg1, arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateTourPackage(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: Array<string>, arg6: TourCategory, arg7: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TourCategory_n9(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTourPackage(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_TourCategory_n9(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
}
async function from_candid_BlogPost_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): Promise<BlogPost> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GalleryPhoto_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryPhoto): Promise<GalleryPhoto> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_TourCategory_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourCategory): TourCategory {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_TourPackage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourPackage): Promise<TourPackage> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    content: string;
    date: bigint;
    published: boolean;
    author: string;
    coverImage: _ExternalBlob;
    category: string;
}): Promise<{
    id: string;
    title: string;
    content: string;
    date: bigint;
    published: boolean;
    author: string;
    coverImage: ExternalBlob;
    category: string;
}> {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        date: value.date,
        published: value.published,
        author: value.author,
        coverImage: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.coverImage),
        category: value.category
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    image: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        image: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: string;
    description: string;
    highlights: Array<string>;
    category: _TourCategory;
    image: _ExternalBlob;
    price: bigint;
}): Promise<{
    id: string;
    title: string;
    duration: string;
    description: string;
    highlights: Array<string>;
    category: TourCategory;
    image: ExternalBlob;
    price: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        description: value.description,
        highlights: value.highlights,
        category: from_candid_TourCategory_n23(_uploadFile, _downloadFile, value.category),
        image: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.image),
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    domestic: null;
} | {
    international: null;
} | {
    honeymoon: null;
}): TourCategory {
    return "domestic" in value ? TourCategory.domestic : "international" in value ? TourCategory.international : "honeymoon" in value ? TourCategory.honeymoon : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Promise<Array<BlogPost>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BlogPost_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryPhoto>): Promise<Array<GalleryPhoto>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryPhoto_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TourPackage>): Promise<Array<TourPackage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TourPackage_n21(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_TourCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TourCategory): _TourCategory {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TourCategory): {
    domestic: null;
} | {
    international: null;
} | {
    honeymoon: null;
} {
    return value == TourCategory.domestic ? {
        domestic: null
    } : value == TourCategory.international ? {
        international: null
    } : value == TourCategory.honeymoon ? {
        honeymoon: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
